services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - http-net
    depends_on:
      - auth-service

  auth-service:
    build: ./services/auth
    env_file:
      - ./services/auth/.env
    volumes:
      - ./services/auth/config:/app/config:ro
    ports:
      - 8081:8080
      - 50001:50000
    networks:
      - http-net
      - auth-net
    depends_on:
      - postgres

  redis:
    image: redis:7.4-alpine
    env_file:
      - .env
    ports:
      - 6379:6379
    networks:
      - auth-net

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    ports: 
      - 5431:5432 # for local
    networks:
      - auth-net

networks:
  http-net:
  auth-net: