services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - http-net
    depends_on:
      - account-service

  account-service:
    build: ./services/account
    env_file:
      - ./services/account/.env
    volumes:
      - ./services/account/config:/app/config:ro
    ports:
      - 8081:8080
      - 50001:50000
    networks:
      - http-net
      - account-net
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    ports: 
      - 5431:5432 # for local
    networks:
      - account-net

networks:
  http-net:
  account-net: